services:
   python:
     image: python:3.10
     volumes:
       - .:/workspaces/python-devcontainer-try
     working_dir: /workspaces/python-devcontainer-try
     command: bash -c "pip install -r requirements.txt && sleep infinity"